@base_url = https://services.odata.org/northwind/northwind.svc
@format = $format=json

### * 1. Get Orders with Customer Details

# Parameters used:
# - $expand=Customer : Includes the full customer details for each order
# - $top=5 : Limits the response to first 5 records because the response is too big

GET {{base_url}}/Orders?$expand=Customer&$top=5&{{format}}
# Response saved in: responses/orders_with_customer.json

### * 2. Get the employees that report to manager “2”.

# Parameters used:
# - $filter=ReportsTo : Allows to filter Employees that just ReportsTo the specified value, in this case '2'
# - $select=Fields : It was used just to simplify the response (it was not necessary)

GET {{base_url}}/Employees?$filter=ReportsTo eq 2&$select=EmployeeID,LastName,FirstName,Title,ReportsTo&{{format}}
# Response saved in: responses/employees_reports_to.json