@base_url = https://services.odata.org/northwind/northwind.svc
@format = $format=json

### * 1. Get Orders with Customer Details

# Parameters used:
# - $expand=Customer : Includes the full customer details for each order
# - $top=5 : Limits the response to first 5 records because the response is too big

GET {{base_url}}/Orders?$expand=Customer&$top=5&{{format}}
# Response saved in: responses/orders_with_customer.json

### * 2. Get the employees that report to manager “2”.

# Parameters used:
# - $filter=ReportsTo : Allows to filter Employees that just ReportsTo the specified value, in this case '2'
# - $select=Fields : It was used just to simplify the response (it was not necessary)

GET {{base_url}}/Employees?$filter=ReportsTo eq 2&$select=EmployeeID,LastName,FirstName,Title,ReportsTo&{{format}}
# Response saved in: responses/employees_reports_to.json

### * 3. Get the products that have stock (inventory).

# Parameters used:
# - $filter=UnitsInStock : Allows to filter Products that have stock (greater than 0)
# - $inlinecount=allpages : Optional but used to know the exact count of products in stock because of the pagination used by the API.
# this means that there are 72 products that are in stock.

GET {{base_url}}/Products?$filter=UnitsInStock gt 0&$inlinecount=allpages&{{format}}
# Response saved in: responses/products_in_stock.json

### * 4. Get only the names and codes of products that are NOT in stock (inventory).

# Parameters used:
# - $filter=UnitsInStock : Allows to filter Products that do NOT have stock (equal to 0)
# - $select=ProductName,ProductID : Used to select just the fields we require.
# - $inlinecount=allpages : Optional but used to know the exact count of products that do NOT have stock because of the pagination used by the API.
# this means that there are 5 products do NOt have stock.

GET {{base_url}}/Products?$filter=UnitsInStock eq 0&$select=ProductName,ProductID&$inlinecount=allpages&{{format}}
# Response saved in: responses/products_without_stock.json

### * 5. Get the 5 most expensive products

# Parameters used:
# - $orderby=UnitPrice desc : Allows to order products by price in descending order (greater to less)
# - $top=5 : After the products are ordered we can select the 5 most expensive products

GET {{base_url}}/Products?$orderby=UnitPrice desc&$top=5&{{format}}
# Response saved in: responses/products_most_expensive.json

### * 6. Find the orders that were sent to “Germany”.

# Parameters used:
# - $filter=ShipCountry : Allows to filter orders by ship country = germany
GET {{base_url}}/Orders?$filter=ShipCountry eq 'Germany'&{{format}}
# Response saved in: responses/order_germany.json

### * 7. Get only the names and prices of the products in the "Beverages" category
# Parameters used:
# - $expand=Category : Includes the category details
# - $filter=Category/CategoryName : Filters by the expanded category name
# - $select : Selects only the product name and price fields

GET {{base_url}}/Products?$expand=Category&$filter=Category/CategoryName eq 'Beverages'&$select=ProductName,UnitPrice&{{format}}
# Response saved in: responses/products_in_beverages_category.json